### PR TITLE
Implement stage 2 import()

### LINKED ISSUE #23: Add support for dynamic import()
From https://github.com/domenic/proposal-import-function

I tried this before and I think acorn doesn't support it, but that can be changed.

### PR DESCRIPTION
**Pull request by matthewp**
This closes #23. Allows modules to dynamically import modules, with
relative paths working as well.

```js
let mod = foo ? './foo.js' : './bar.js';

import(mod).then(fooNamespace => {

});
```

### CODE REVIEW

**Comment by matthewp** [comment]
Not ready yet, still need to:

* [ ] - Test error case
* [ ] - Test when passed an absolute url

And probably more.

**Comment by domenic** [comment]
Hmm, the test seems to be testing a `importDynamic()` function that uses script tags and thus URLs, not an `import()` syntactic form that uses module specifiers? I'm probably missing something.

**Comment by matthewp** [comment]
That's used to run the tests, here's the syntactic form: https://github.com/matthewp/script-type-module/pull/27/files#diff-6ec0bda4148a2be83417930f625243c4R3

**Comment by domenic** [comment]
Ah awesome, thanks!

**Pull request merged**
